### ISSUE TITLE
Validating generated csv files

### ISSUE THREAD

**Issue by peterdesmet** [enram/vptstools#10]
@stijnvanhoey CSV files can be validated with:

1. Create a `datapackage.json` file with the following content:

```
{
  "profile": "tabular-data-package",
  "resources": [
    {
      "name": "vpts",
      "path": "vpts.csv",
      "profile": "tabular-data-resource",
      "format": "csv",
      "mediatype": "text/csv",
      "encoding": "utf-8",
      "schema": "https://raw.githubusercontent.com/enram/vpts-csv/main/vpts-csv-table-schema.json"
    }
  ]
}
```

2. Place the `datapackage.json` file in the same directory as your CSV file. Rename the `path` value if necessary to point to the CSV file (above named `vpts.csv`).
3. Install https://github.com/frictionlessdata/frictionless-py, I'm using v4.40.0
4. Running in CLI: `frictionless validate datapackage.json`

**Comment by stijnvanhoey** [comment]
handles on frictionless so-called "resource" level in https://github.com/enram/vptstools/pull/19
