### ISSUE TITLE
Convert VCP `0` to `NULL`

### ISSUE THREAD

**Issue by peterdesmet** [enram/vptstools#14]
See https://github.com/enram/vpts-csv/issues/38#issuecomment-1349684448

**Comment by stijnvanhoey** [comment]
@peterdesmet just to be clear:

Incoming (historical) vcp data can be an integer and if the value is zero, we convert to "" (or more general,  what we define in the VPTSclass as the 'nodata' property). With the [update of Adriaan](https://github.com/adokter/vol2bird/issues/198), the value can also be NULL and we convert this to "" as well (or more general,  what we define in the VPTSclass as the 'nodata' property).  See https://github.com/enram/vptstools/commit/845d171e49a67357463f46dfc0e1ec295132b3db

**Comment by peterdesmet** [comment]
Correct.

**Comment by stijnvanhoey** [comment]
part of https://github.com/enram/vptstools/pull/19, closing this one
