### ISSUE TITLE
Move `generate_coverage.py` as function to vptstools

### ISSUE THREAD

**Issue by peterdesmet** [enram/vptstools#18]
Cf. #17 @stijnvanhoey, you probably have already started with this?

Note that the `generate_coverage.py` might no longer be needed if we use AWS Inventory.

**Comment by stijnvanhoey** [comment]
Indeed, this will be replaced by the inventory based code. Will close this once the operational code of https://github.com/enram/vptstools/pulls is properly checked.

**Comment by stijnvanhoey** [comment]
Fixed by https://github.com/enram/vptstools/pull/45
