### ISSUE TITLE
Add validate_vpts function optional parameter to reference a specific vpts-csv schema (e.g. version="v1")

### ISSUE THREAD

**Issue by stijnvanhoey** [enram/vptstools#21]
https://github.com/enram/vptstools/blob/6a6953490e571a3a383c70a501f9d7352744c931/src/vptstools/vpts.py#L476

-> by only adjusting the url so `report = validate_vpts(df_vpts, version="v1")` becomes possible

**Comment by stijnvanhoey** [comment]
@peterdesmet how will, the vpts-csv-table-schema be versioned and will there be a logic to translate a version (e.g. 'v1' to the URL). An alternative is to let the user provide a URL as input of the validation functionality.

**Comment by peterdesmet** [comment]
The URL will contain `v1.0`

**Comment by peterdesmet** [comment]
https://raw.githubusercontent.com/enram/vpts-csv/v1.0/vpts-csv-table-schema.json is now accessible
