### ISSUE TITLE
Verify NULL values in ff, dd , sd_vvp, eta properties

### ISSUE THREAD

**Issue by stijnvanhoey** [enram/vptstools#23]
See https://github.com/enram/vpts-csv/issues/40#issuecomment-1350572267

> did you also encounter NULL (rather than NaN) values for these properties?

Need to double check this for ff, dd , sd_vvp, eta

**Comment by peterdesmet** [comment]
@stijnvanhoey have you checked this? https://github.com/enram/vpts-csv/pull/42 is pending this issue.

**Comment by stijnvanhoey** [comment]
Actually, for the files I checked (subset of the files for different countries/radars), but I assume others are processed similarly, the 

- nodata value in the HDF5-file is "-1000" (/dataset1/data1/what/nodata), which is mapped for the vpts-csv to "" (empty string
- undetect value in the HDF5-file is "-999" (/dataset1/data1/what/undetect), which is mapped for the vpts-csv to "NaN"

for each of those variables. So no 'NULL' is in the data itself, but I do encounter both the nodata (-1000) and undetect (-999) values in the data.  Hence, I do think you should not make them required.
