### ISSUE TITLE
How to handle the gain/offset in the conversion from hdf5 to vpts-csv

### ISSUE THREAD

**Issue by stijnvanhoey** [enram/vptstools#32]
In the https://github.com/adokter/vol2bird/wiki/ODIM-bird-profile-format-specification#specification-of-bird-profile-output-in-odim-hdf5-format specification there is a `gain` and an `offset` for the datasets/variables. In the conversion from h5 to vpts-CSV, the current implementation does not take these into account. @adokter, should this actually be done by default and store in the vpts-csv version for each record `quantity*gain+offset` instead of the `quantity`?

**Comment by adokter** [comment]
Hi @stijnvanhoey, I would define the value as quantity*gain+offset, following the ODIM standard. Currently the vp files use gain=1 and offset=0, so it doesn't make a numerical difference. But better to adhere to the data standard in case that would ever change.

**Comment by stijnvanhoey** [comment]
Thanks for the input, the gain/offset is included as part of the https://github.com/enram/vptstools/pull/19 refactoring
