### ISSUE TITLE
Use environmental variables for BALTRAD sync

### ISSUE THREAD

**Issue by peterdesmet** [enram/vptstools#41]

**Comment by stijnvanhoey** [comment]
As discussed with @TheJenne18:

- transfer CLI -> env vars: FTP_HOST, FTP_PORT, FTP_USERNAME, FTP_PWD, FTP_DATADIR, BUCKET, SNS_TOPIC
- daily/monthly -> BUCKET, INVENTORY_BUCKET, SNS_TOPIC

@stijnvanhoey will do the refactoring asap so the deployment can be adjusted

**Comment by stijnvanhoey** [comment]
Fixed by https://github.com/enram/vptstools/pull/45
