### ISSUE TITLE
Cannot unzip gzip data

### ISSUE THREAD

**Issue by peterdesmet** [enram/vptstools#42]
Monthly data, e.g. https://aloft.s3-eu-west-1.amazonaws.com/baltrad/monthly/bejab/2023/bejab_vpts_202302.csv.gz return an error when trying to unzip on Mac:

<img width="490" alt="Screenshot 2023-05-16 at 10 19 13" src="https://github.com/enram/vptstools/assets/600993/22d9e566-e4b3-4877-96f1-da6447b9d134">

**Comment by niconoe** [comment]
I confirm I can reproduce this.

Would it be [this bug](https://apple.stackexchange.com/questions/388759/archive-utility-cant-open-some-gzipped-text-files-based-on-their-contents) from Archive utility?

If so, not much to do until Apple release a fix...

**Comment by peterdesmet** [comment]
@dimevil was able to open on Windows and @stijnvanhoey on Linux, so this does seem Mac OS related. Closing here.
