### ISSUE TITLE
Provide some more info in AWS notifications

### ISSUE THREAD

**Issue by peterdesmet** [enram/vptstools#48]
I'm getting daily AWS notifications with:

> CLI routine 'vph5_to_vpts --modified-days-ago 2' failed raising error: '<class 'ValueError'>: File name is not a valid ODIM h5 file.'.

It would be helpful to:

- [ ] Know what file failed
- [ ] ~Where the log files can be found (Cloudwatch link)~ decided to keep this part out of functionality

**Comment by stijnvanhoey** [comment]
See https://github.com/enram/vptstools/pull/54
