### ISSUE TITLE
Manage tags/releases

### ISSUE THREAD

**Issue by peterdesmet** [enram/vptstools#63]
I notice we have [many tags](https://github.com/enram/vptstools/tags) and 1 release. @stijnvanhoey:

1. Is a `tag` sufficient to have it be picked up by GitHub Actions and used in the operational pipeline? Or does it require a release.
2. Is a `tag` sufficient to have it be published to PyPi? **Yes, see https://pypi.org/project/vptstools/**
3. Should we create releases for the most recent tags? Maybe only for the minor versions (not hotfixes)
4. Should we clean up the tags, there seems to be a mixed of usage. Here's my suggestion

- [x] v0.2.2: keep
- [x] v0.2.1: keep
- [x] v0.2.0: keep
- [x] 0.1.0a14: delete
- [x] 0.1.0a13: delete
- [x] v0.1.0: keep, is release
- [x] 0.1.0a12: delete
- [x] 0.1.0a11: delete
- [x] 0.1.0a10: delete
- [x] 0.1.0a9: delete
- [x] 0.1.0a8: delete
- [x] 0.1.0a7: delete
- [x] 0.1.0a6: delete
- [x] 0.1.0a5: delete
- [x] 0.1.0a4: delete
- [x] 0.1.0a3: delete
- [x] 0.1.0a2: delete
- [x] 0.1.0a1: delete

**Comment by stijnvanhoey** [comment]
1. and 2. -> yes indeed this is enough; we could change that by adjusting the release.yml github action, see https://github.com/enram/vptstools/blob/v0.2.2/.github/workflows/release.yml#L8-L9
3. I would create releases for each tag after cleanup
4. I agree on removing the alpha tags

**Comment by peterdesmet** [comment]
1. I think it's fine to leave as tags, we'll just have to be clear in our terraform documentation that that is sufficient
3. Ok, 0.2.0 and 0.2.1 have no releases (would not know to describe them), but that's fine
4. I have removed the alpha tags

**Comment by peterdesmet** [comment]
All tags except the v0.2.0 and v0.2.1 are now described as releases.
